// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAffQ7432ud3tkHiBuXaNg3ReG3SNOedgc',
    appId: '1:568076250884:web:31b46446d55de8a54a6a51',
    messagingSenderId: '568076250884',
    projectId: 'mood-journal-51232',
    authDomain: 'mood-journal-51232.firebaseapp.com',
    storageBucket: 'mood-journal-51232.firebasestorage.app',
    measurementId: 'G-VWPTRF9G6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR9lwvVtfXelF1cQ4tz0BtUn__TRU1jdY',
    appId: '1:568076250884:android:be477db6708bce504a6a51',
    messagingSenderId: '568076250884',
    projectId: 'mood-journal-51232',
    storageBucket: 'mood-journal-51232.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGrwi0VfFtbeY2q15NnVT7TC-TFq8S5-M',
    appId: '1:568076250884:ios:9307a55098d246184a6a51',
    messagingSenderId: '568076250884',
    projectId: 'mood-journal-51232',
    storageBucket: 'mood-journal-51232.firebasestorage.app',
    iosBundleId: 'com.moodjournal.moodJournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAffQ7432ud3tkHiBuXaNg3ReG3SNOedgc',
    appId: '1:568076250884:web:a8d5dc308391fff34a6a51',
    messagingSenderId: '568076250884',
    projectId: 'mood-journal-51232',
    authDomain: 'mood-journal-51232.firebaseapp.com',
    storageBucket: 'mood-journal-51232.firebasestorage.app',
    measurementId: 'G-JB01RNZ0WB',
  );
}
